### PR TITLE
Update manpages to 5.11 and build them using Github Actions

### PR DESCRIPTION
**Pull request by cmorty**
I had to drop the support for compressed man pages, as man2html wasn't able to handle the `.SO` command otherwise.

Every commit is now build using Github Actions and the result is saved as Artifact. A tag results in a draft release, which can be adjusted before it is made public.

Of course I also hope that https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Linux_Man_Pages will also be updated. ;)

### CODE REVIEW

**Comment by cmorty** [comment]
I didn't review the result thoroughly, but will do so tomorrow, but I wanted to finish my day with a success. ;)

**Comment by Yanpas** [comment]
Thanks for PR!

However compressed man pages were requested for creating docset from man pages located somewhere in /usr. And decompression shouldn't make any difference. Could you provide file that doesn't work with master's version?

**Comment by cmorty** [comment]
@Yanpas  Try downloading the files from https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/ . They contain quite a few `.SO` commands, referencing other files. This would have to be handled in python. However, on my local system man2html handles gz compressed man pages just fine.

**Comment by Yanpas** [comment]
Pandoc should handle them fine. Pandoc doesn't support compressed input, so please revert compression removal

**Comment by cmorty** [comment]
As I said: Using compression does not work with the latest linux man-pages.... - And I'm not really willing to invest the time to implement `.SO` in python -> Close?

**Pull request closed without merging**
